src/django/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy


from . import views

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path(
            "accounts/login/",
            auth_views.LoginView.as_view(
                redirect_authenticated_user=True, next_page="home"
            ),
            name="login",
        ),
        path(
            "accounts/logout/",
            auth_views.LogoutView.as_view(next_page="login"),
            name="logout",
        ),
        path(
            "accounts/password-reset/",
            auth_views.PasswordResetView.as_view(),
            name="password_reset",
        ),
        path(
            "accounts/password-reset/done/",
            auth_views.PasswordResetDoneView.as_view(),
            name="password_reset_done",
        ),
        path(
            "accounts/reset/<uidb64>/<token>/",
            auth_views.PasswordResetConfirmView.as_view(),
            name="password_reset_confirm",
        ),
        path(
            "accounts/reset/done/",
            auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete",
        ),
        path(
            "accounts/password-change",
            views.CustomPasswordChangeView.as_view(),
            name="password-change",
        ),
        path("", RedirectView.as_view(url=reverse_lazy("home"))),
        path(
            "app/",
            include(
                [
                    path("", views.home, name="home"),
                    path("busqueda/", views.Search.as_view(), name="search"),
                    path("administracion/", views.dashboard, name="dashboard"),
                    path("carreras/", include("carreras.urls")),
                    path("profesores/", include("profesores.urls")),
                    path("salones/", include("salones.urls")),
                    path("clases/", include("clases.urls")),
                    path("perfil/", include("profiles.urls")),
                    path("estudiantes/", include("estudiantes.urls")),
                    path("pagos/", include("pagos.urls")),
                ]
            ),
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

src/django/estudiantes/urls.py
from django.urls import path
from . import views


app_name = "estudiantes"

urlpatterns = [
    path("", views.AlumnoListView.as_view(), name="students"),
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path(
        "ficha-del-estudiante/nuevo",
        views.AlumnoCreateView.as_view(),
        name="create-student",
    ),
    path(
        "inscripcion/<slug>/nuevo",
        views.InscripcionNueva.as_view(),
        name="enrolment-student",
    ),
    path(
        "inscripcion/<slug>/bajar",
        views.BajaEstudiante.as_view(),
        name="resign-student",
    ),
    path("<slug>/detalle", views.AlumnoDetailView.as_view(), name="detail-student"),
    path("<slug>/editar", views.AlumnoUpdateView.as_view(), name="update-student"),
    path("<slug>/eliminar", views.AlumnoDeleteView.as_view(), name="delete-student"),
    path(
        "<slug>/inhabilitar",
        views.InhabilitarAlumno.as_view(),
        name="disable-student",
    ),
    path(
        "<slug>/habilitar",
        views.HabilitarAlumno.as_view(),
        name="enable-student",
    ),
    path(
        "grupos/",
        views.Groups.as_view(),
        name="groups",
    ),
    path(
        "cambiar/<slug>/grupo/<id>/", views.CambioDeGrupo.as_view(), name="change-group"
    ),
]

src/django/templates/base/components/action buttons/crud_actions.html
<div class="flex flex-row items-end text-base font-semibold text-white">
    <a href="{% url 'estudiantes:detail-student' student.slug %}" class='mr-2'>
      <svg class="w-6 h-6 text-white  hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
        <path fill-rule="evenodd" d="M4.998 7.78C6.729 6.345 9.198 5 12 5c2.802 0 5.27 1.345 7.002 2.78a12.713 12.713 0 0 1 2.096 2.183c.253.344.465.682.618.997.14.286.284.658.284 1.04s-.145.754-.284 1.04a6.6 6.6 0 0 1-.618.997 12.712 12.712 0 0 1-2.096 2.183C17.271 17.655 14.802 19 12 19c-2.802 0-5.27-1.345-7.002-2.78a12.712 12.712 0 0 1-2.096-2.183 6.6 6.6 0 0 1-.618-.997C2.144 12.754 2 12.382 2 12s.145-.754.284-1.04c.153-.315.365-.653.618-.997A12.714 12.714 0 0 1 4.998 7.78ZM12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" clip-rule="evenodd"/>
      </svg>                            
    </a>
    <a href="{% url 'estudiantes:update-student' student.slug %}" class='mr-2'>
      <svg class="w-6 h-6 text-white  hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
        <path fill-rule="evenodd" d="M11.32 6.176H5c-1.105 0-2 .949-2 2.118v10.588C3 20.052 3.895 21 5 21h11c1.105 0 2-.948 2-2.118v-7.75l-3.914 4.144A2.46 2.46 0 0 1 12.81 16l-2.681.568c-1.75.37-3.292-1.263-2.942-3.115l.536-2.839c.097-.512.335-.983.684-1.352l2.914-3.086Z" clip-rule="evenodd"/>
        <path fill-rule="evenodd" d="M19.846 4.318a2.148 2.148 0 0 0-.437-.692 2.014 2.014 0 0 0-.654-.463 1.92 1.92 0 0 0-1.544 0 2.014 2.014 0 0 0-.654.463l-.546.578 2.852 3.02.546-.579a2.14 2.14 0 0 0 .437-.692 2.244 2.244 0 0 0 0-1.635ZM17.45 8.721 14.597 5.7 9.82 10.76a.54.54 0 0 0-.137.27l-.536 2.84c-.07.37.239.696.588.622l2.682-.567a.492.492 0 0 0 .255-.145l4.778-5.06Z" clip-rule="evenodd"/>
      </svg>
    </a>
    <a class="cursor-pointer" data-modal-target="confirm-modal" data-modal-toggle="confirm-modal" hx-get="{% url 'estudiantes:delete-student' student.slug %}" hx-target="#confirm-form" hx-trigger="click" hx-swap="innerHTML">
      <svg class="w-6 h-6 text-red-400  hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
        <path fill-rule="evenodd" d="M8.586 2.586A2 2 0 0 1 10 2h4a2 2 0 0 1 2 2v2h3a1 1 0 1 1 0 2v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8a1 1 0 0 1 0-2h3V4a2 2 0 0 1 .586-1.414ZM10 6h4V4h-4v2Zm1 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Zm4 0a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Z" clip-rule="evenodd"/>
      </svg>                            
    </a>
</div>