src/django/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy


from . import views

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path(
            "accounts/login/",
            auth_views.LoginView.as_view(
                redirect_authenticated_user=True, next_page="home"
            ),
            name="login",
        ),
        path(
            "accounts/logout/",
            auth_views.LogoutView.as_view(next_page="login"),
            name="logout",
        ),
        path(
            "accounts/password-reset/",
            auth_views.PasswordResetView.as_view(),
            name="password_reset",
        ),
        path(
            "accounts/password-reset/done/",
            auth_views.PasswordResetDoneView.as_view(),
            name="password_reset_done",
        ),
        path(
            "accounts/reset/<uidb64>/<token>/",
            auth_views.PasswordResetConfirmView.as_view(),
            name="password_reset_confirm",
        ),
        path(
            "accounts/reset/done/",
            auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete",
        ),
        path(
            "accounts/password-change",
            views.CustomPasswordChangeView.as_view(),
            name="password-change",
        ),
        path("", RedirectView.as_view(url=reverse_lazy("home"))),
        path(
            "app/",
            include(
                [
                    path("", views.home, name="home"),
                    path("busqueda/", views.Search.as_view(), name="search"),
                    path("administracion/", views.dashboard, name="dashboard"),
                    path("carreras/", include("carreras.urls")),
                    path("profesores/", include("profesores.urls")),
                    path("salones/", include("salones.urls")),
                    path("clases/", include("clases.urls")),
                    path("perfil/", include("profiles.urls")),
                    path("estudiantes/", include("estudiantes.urls")),
                    path("pagos/", include("pagos.urls")),
                ]
            ),
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

src/django/pagos/urls.py
from django.urls import path
from . import views

app_name = "pagos"


urlpatterns = [
    path("agregar-pago/<slug>/", views.create_pago, name="add-payment"),
    path("modificar-pago/<pk>/", views.update_pago, name="update-payment"),
    path("detalle-pago/<pk>/", views.DetailPago.as_view(), name="detail-payment"),
    path("<slug>/pagos", views.ListPagos.as_view(), name="payments"),
    path("eliminar-pago/<pk>/", views.DeletePago.as_view(), name="delete-payment"),
]

src/django/pagos/models.py
from django.db import models

# Create your models here.

src/django/pagos/forms.py
from django import forms
from django.core.exceptions import ValidationError
from domain.models import Pago, Alumno, AlumnoCurso, Curso


class PagoForm(forms.ModelForm):
    alumno = forms.SlugField()

    class Meta:
        model = Pago
        fields = ["monto", "fecha", "descripcion", "comprobante", "curso"]
        exclude = ["alumno"]

    fecha = forms.DateTimeField(
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "bg-gray-900 divide-y divide-gray-100  shadow dark:bg-gray-700",
            }
        )
    )

    def __init__(self, *args, **kwargs):
        super(PagoForm, self).__init__(*args, **kwargs)
        if initial := kwargs.get("initial"):
            if "student_slug" in initial:
                student_slug = initial["student_slug"]
                if student_slug:
                    student = Alumno.objects.get(slug=student_slug)
                    self.fields["alumno"].widget = forms.HiddenInput(
                        attrs={"value": student.slug}
                    )
                    enrolled_courses = AlumnoCurso.objects.filter(
                        alumno=student
                    ).values_list("curso__pk", "curso__nombre")
                    self.fields["curso"] = forms.ChoiceField(
                        choices=enrolled_courses,
                        widget=forms.Select(attrs={"class": "form-control"}),
                    )
            if "fecha" in self.initial:
                self.initial["fecha"] = self.initial["fecha"].strftime("%Y-%m-%d")
                self.fields["fecha"].widget.attrs.update(
                    {
                        "class": "bg-gray-900 divide-y divide-gray-100  shadow dark:bg-gray-700"
                    }
                )

        if kwargs.get("instance"):
            if kwargs["instance"].alumno:
                student_slug = kwargs["instance"].alumno.slug
                super(PagoForm, self).__init__(*args, **kwargs)
                if student_slug:
                    student = Alumno.objects.get(slug=student_slug)
                    self.fields["alumno"].widget = forms.HiddenInput(
                        attrs={"value": student.slug}
                    )
                    enrolled_courses = AlumnoCurso.objects.filter(
                        alumno=student
                    ).values_list("curso__pk", "curso__nombre")
                    self.fields["curso"] = forms.ChoiceField(
                        choices=enrolled_courses,
                        widget=forms.Select(attrs={"class": "form-control"}),
                    )
            if kwargs["instance"].fecha:
                self.initial["fecha"] = kwargs["instance"].fecha.strftime("%Y-%m-%d")

    def clean_monto(self):
        monto = self.cleaned_data["monto"]
        if monto <= 0:
            raise ValidationError("El monto debe ser mayor a $0.00")

        return monto

    def clean_alumno(self):
        slug = self.cleaned_data["alumno"]
        try:
            alumno = Alumno.objects.get(slug=slug)
            return alumno
        except Alumno.DoesNotExist:
            raise ValidationError("No existe alumno")

    def clean_curso(self):
        curso_id = self.cleaned_data["curso"]
        try:
            curso = Curso.objects.get(pk=curso_id)

            return curso
        except Curso.DoesNotExist:
            raise ValidationError("No existe curso")

    def clean(self):
        cleaned_data = super().clean()
        alumno = cleaned_data.get("alumno")
        curso = cleaned_data.get("curso")
        fecha_pago = cleaned_data.get("fecha")
        mes_actual = fecha_pago.month
        anio_actual = fecha_pago.year

        pago_en_mes_actual = Pago.objects.filter(
            alumno=alumno, curso=curso, fecha__month=mes_actual, fecha__year=anio_actual
        )

        if (
            pago_en_mes_actual.exists()
            and pago_en_mes_actual.first().id != self.instance.id
        ):
            raise forms.ValidationError(
                "El alumno ya ha realizado un pago para este curso en el mes actual."
            )

        return cleaned_data

    def save(self, commit=True):
        instance = super(PagoForm, self).save(commit=False)
        instance.alumno = self.cleaned_data["alumno"]
        if commit:
            instance.save()
        return instance

src/django/pagos/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, DeleteView
from domain.models import Alumno, Pago
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PagoForm


def create_pago(request: HttpRequest, slug: str) -> HttpResponseRedirect:
    student = Alumno.objects.get(slug=slug)
    if request.method == "POST":
        form = PagoForm(
            request.POST, request.FILES, initial={"student_slug": student.slug}
        )

        if form.is_valid():
            pago = form.save(commit=False)
            pago.alumno = student
            pago.save()
            return HttpResponse()
        else:
            response = render(
                request, "pagos/pago_form.html", {"form": form, "slug": student.slug}
            )
            response["HX-Retarget"] = "#payment-modal"

            return response
    else:
        form = PagoForm(initial={"student_slug": student.slug})
    return render(request, "pagos/pago_form.html", {"form": form, "slug": student.slug})


def update_pago(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    pago = get_object_or_404(Pago, pk=pk)
    student = pago.alumno
    if request.method == "POST":
        form = PagoForm(request.POST, request.FILES, instance=pago)
        if form.is_valid():
            form.save()
            return HttpResponse()
        else:
            response = render(
                request,
                "pagos/update_pago_form.html",
                {"form": form, "pago": pago, "student": student},
            )
            response["HX-Retarget"] = "#payment-modal"
            return response
    else:
        form = PagoForm(instance=pago)
    return render(
        request,
        "pagos/update_pago_form.html",
        {"form": form, "pago": pago, "student": student},
    )


class DeletePago(LoginRequiredMixin, DeleteView):
    model = Pago
    template_name = "pagos/pago_confirm_delete.html"

    def get_success_url(self):
        student = self.kwargs["slug"]
        return reverse_lazy("pagos:payments", kwargs={"slug": student})


class DetailPago(LoginRequiredMixin, DetailView):
    model = Pago
    template_name = "pagos/pago_detail.html"


class ListPagos(LoginRequiredMixin, ListView):
    model = Pago
    template_name = "pagos/pago_list.html"
    context_object_name = "lista_pagos"

    def get(self, request, *args, **kwargs):
        student = Alumno.objects.get(slug=kwargs["slug"])
        pagos = Pago.objects.filter(alumno=student)

        context = {
            "payment_list": pagos,
            "student": student,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        student = Alumno.objects.get(slug=kwargs["slug"])
        pagos = Pago.objects.filter(alumno=student)

        context = {
            "payment_list": pagos,
            "student": student,
        }
        return render(request, self.template_name, context)


class DetailPago(LoginRequiredMixin, DetailView):
    model = Pago
    template_name = "pagos/pago_detail.html"

    def get(self, request, *args, **kwargs):
        pago = get_object_or_404(Pago, id=kwargs["pk"])
        student = pago.alumno

        context = {
            "pago": pago,
            "student_slug": student.slug,
        }
        return render(request, self.template_name, context)


class DeletePago(LoginRequiredMixin, DeleteView):
    model = Pago
    template_name = "pagos/pago_confirm_delete.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Pago, id=self.kwargs["pk"])

    def get_success_url(self):
        student = self.object.alumno
        return reverse_lazy("pagos:payments", kwargs={"slug": student.slug})

src/django/pagos/templates/pagos/pago_confirm_delete.html
<form method="post" action="{% url 'pagos:delete-payment' pk=pago.pk  %}">{% csrf_token %}
    <svg class="mx-auto mb-4 w-12 h-12 text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
    </svg>
    <h3 class="mb-5 text-lg font-normal text-gray-400">¿Confirmás que querés eliminar a este pago?</h3>
    <input value="Sí, seguro." data-modal-hide="popup-modal" type="submit" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-800 font-medium rounded text-sm inline-flex items-center px-5 py-2.5 text-center">
</form>

src/django/pagos/templates/pagos/pago_detail.html
<h1>Detalles del pago</h1>

{% if pago.fecha %}
<p>Fecha: {{ pago.fecha }}</p>
{%else%}
<p>Fecha: No disponible</p>
{% endif %}

{% if pago.monto %}
<p>Monto: {{ pago.monto }}</p>
{% else %}
<p>Monto: No disponible</p>
{% endif %}
{% if pago.curso %}
<p>Curso: {{ pago.curso.nombre }}</p>
{% else %}
<p>Monto: No disponible</p>
{% endif %}
{% if pago.descripcion %}
<p>Descripción: {{ pago.descripcion }}</p>
{% else %}
<p>Descripción: No disponible</p>
{% endif %}
{% if pago.comprobante %}
<p>Comprobante: <a  style=" text-decoration: underline" href="{{ pago.comprobante.url }}">Ver comprobante</a ></p>
{% else %}
<p>Comprobante: No disponible</p>
{% endif %}



<a  class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-800 font-medium rounded text-sm inline-flex items-center px-5 py-2.5 text-center" href="{% url 'pagos:payments' student_slug  %}">Volver a la lista de pagos</a>

src/django/pagos/templates/pagos/pago_form.html
<form hx-post="{% url 'pagos:add-payment' slug %}"  enctype="multipart/form-data" class="col-span-3 md:col-span-2 lg:col-span-2 max-w-full bg-gray-900 border border-gray-700 rounded p-8 payment-form ">
  {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
        {{ form.non_field_errors }}

    </div>
    <div>
        {% for field in form %}
        {% if field.errors %}
            {{ field.label_tag }}
            {% for error in field.errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
    {% endfor %}
    </div>
    {% endif %}

    <div class="flex flex-col mb-4">
        <label  for="id_alumno"></label>
        {{ form.alumno }}
    </div>
    <div class="flex flex-col mb-4">
        {{form.curso.label_tag}}
        {{form.curso}}
    </div>

    <div class="flex flex-col mb-4">
        {{form.monto.label_tag}}
        {{form.monto}}
    </div>
    <div class="flex flex-col mb-4">
        {{form.fecha.label_tag}}
        {{form.fecha}}
    </div>

    <div class="flex flex-col mb-4">
        {{form.descripcion.label_tag}}
        {{form.descripcion}}
    </div>
    <div class="flex flex-col mb-4">
        {{form.comprobante.label_tag}}
        {{form.comprobante}}
    </div>
    <input class='main-action-button w-full' type="submit" value="Guardar">
</form>

src/django/pagos/templates/pagos/pago_list.html
{% extends 'base.html' %}

{% block navbar %}
  {% include 'base/components/navbar.html' %}
{% endblock %}

{% block sidebar %}
  {% include 'base/components/sidebar.html' %}
{% endblock %}

{% block breadcrumb %}
<nav class="col-span-3 flex pl-4" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="{% url 'home' %}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-accent-500 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li class="inline-flex items-center">
        <a href="{{student.get_absolute_url}}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-accent-500 dark:text-gray-400 dark:hover:text-white">
            <svg class="w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
              </svg>
              {{student.apellido}}, {{student.nombre}}
        </a>
      </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Pagos</span>
      </div>
    </li>
  </ol>
</nav>
{% endblock %}

{% block content %}
<section class='col-span-3 md:col-span-2 lg:col-span-2'>
  <div class="w-full max-w-full p-4 bg-gray-900 border border-gray-700 rounded shadow sm:p-8">
    <div class="flex items-center justify-between mb-4">
        <h5 class="text-xl font-bold leading-nonetext-white">Pagos</h5>
        <a href="#" hx-get="{% url 'pagos:add-payment' student.slug %}" hx-trigger="click" hx-swap="innerHTML"  hx-target="#payment-form" data-modal-target="payment-modal" data-modal-toggle="payment-modal"  >
          <svg class="text-sm font-medium text-white hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4.243a1 1 0 1 0-2 0V11H7.757a1 1 0 1 0 0 2H11v3.243a1 1 0 1 0 2 0V13h3.243a1 1 0 1 0 0-2H13V7.757Z" clip-rule="evenodd"/>
          </svg>
        </a>

    </div>
{%if payment_list %}
   <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
            {% for pago in payment_list %}
              {% include 'pagos/components/pago_list_component.html' %}
            {% endfor %}
        </ul>
   </div>
  </div>

  {%else%}
  <div
  class="container bg-gray-950 p-8 lg:rounded mx-auto pt-32 shadow-md lg:pt-8 max-w-lg lg:w-auto"
  >

  <h2 class="text-xl font-semibold text-yellow-400 mx-auto">
      No hay pagos.
    </h2>

</div>
{%endif%}
</section>

<div id="confirm-modal" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-md max-h-full">
      <div class="relative rounded shadow bg-gray-900 border border-gray-700">
          <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center hover:bg-gray-600 hover:text-white" data-modal-hide="confirm-modal">
              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
              </svg>
              <span class="sr-only">Cerrar modal</span>
          </button>
          <div id="confirm-form" class="p-4 md:p-5 text-center">
          </div>
      </div>
  </div>
</div>


<div id="payment-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-md max-h-full">
      <!-- Modal content -->
      <div class="relative rounded-lg shadow bg-gray-900 border border-gray-700">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
              <h3 class="text-lg font-semibold text-white">
                  Pagos
              </h3>
              <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="payment-modal">
                  <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                  </svg>
                  <span class="sr-only">Cerrar modal</span>
              </button>
          </div>
          <!-- Modal body -->

          <div id="payment-form" class="payment-form">
          </div>
      </div>
  </div>
</div>
{% endblock %}

src/django/pagos/templates/pagos/update_form.html
<html>
    <head>
        <title>UpdateView</title>

    </head>

    <body>
<form method="POST"   >{% csrf_token %}

<!-- form variable -->
 {{ form.as_p }}

  <input type="submit" name="sumbit">
</form>
    </body>

</html>

src/django/pagos/templates/pagos/update_pago_form.html
<form hx-post="{% url 'pagos:update-payment' pago.pk %}" enctype="multipart/form-data" class="col-span-3 md:col-span-2 lg:col-span-2 max-w-full bg-gray-900 border border-gray-700 rounded p-8 payment-form ">
  {% csrf_token %}
  <h5 class="text-xl font-bold leading-nonetext-white">Modificar Pago</h5>
  <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700"/>
  {{ form.errors }}

    <div class="flex flex-col mb-4">
        <label for="id_alumno"></label>
        {{ form.alumno }}
    </div>
    <div class="flex flex-col mb-4">
        {{form.curso.label_tag}}
        {{form.curso}}
    </div>
    <div class="flex flex-col mb-4">
        {{form.monto.label_tag}}
        {{form.monto}}
    </div>
    <div class="flex flex-col mb-4">
        {{form.fecha.label_tag}}
        {{form.fecha}}
    </div>
    <div class="flex flex-col mb-4">
        {{form.descripcion.label_tag}}
        {{form.descripcion}}
    </div>
    <div class="flex flex-col mb-4">
        {{form.comprobante.label_tag}}
        {{form.comprobante}}
    </div>
    <input class='main-action-button w-full' type="submit" value="Guardar">
</form>