src/django/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy


from . import views

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path(
            "accounts/login/",
            auth_views.LoginView.as_view(
                redirect_authenticated_user=True, next_page="home"
            ),
            name="login",
        ),
        path(
            "accounts/logout/",
            auth_views.LogoutView.as_view(next_page="login"),
            name="logout",
        ),
        path(
            "accounts/password-reset/",
            auth_views.PasswordResetView.as_view(),
            name="password_reset",
        ),
        path(
            "accounts/password-reset/done/",
            auth_views.PasswordResetDoneView.as_view(),
            name="password_reset_done",
        ),
        path(
            "accounts/reset/<uidb64>/<token>/",
            auth_views.PasswordResetConfirmView.as_view(),
            name="password_reset_confirm",
        ),
        path(
            "accounts/reset/done/",
            auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete",
        ),
        path(
            "accounts/password-change",
            views.CustomPasswordChangeView.as_view(),
            name="password-change",
        ),
        path("", RedirectView.as_view(url=reverse_lazy("home"))),
        path(
            "app/",
            include(
                [
                    path("", views.home, name="home"),
                    path("busqueda/", views.Search.as_view(), name="search"),
                    path("administracion/", views.dashboard, name="dashboard"),
                    path("carreras/", include("carreras.urls")),
                    path("profesores/", include("profesores.urls")),
                    path("salones/", include("salones.urls")),
                    path("clases/", include("clases.urls")),
                    path("perfil/", include("profiles.urls")),
                    path("estudiantes/", include("estudiantes.urls")),
                    path("pagos/", include("pagos.urls")),
                ]
            ),
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

src/django/clases/urls.py
from django.urls import path
from . import views

app_name = "clases"

urlpatterns = [
    path(
        "bloques/crear/<int:pk>/",
        views.CreateBloqueDeClase.as_view(),
        name="create-class-block",
    ),
    path("bloques/", views.ListBloqueDeClases.as_view(), name="list-class-blocks"),
    path(
        "bloques/<int:pk>/detalle",
        views.DetailBloqueDeClase.as_view(),
        name="detail-class-block",
    ),
    path(
        "bloques/<int:pk>/editar",
        views.BloqueClaseUpdateView.as_view(),
        name="update-class-block",
    ),
    path(
        "bloques/<int:pk>/eliminar",
        views.DeleteBloqueDeClase.as_view(),
        name="delete-class-block",
    ),
    path("", views.list_groups, name="list-groups"),
    path("grupos/crear", views.CreateGrupo.as_view(), name="create-group"),
    path("grupos/<int:pk>/editar", views.UpdateGrupo.as_view(), name="update-group"),
    path("grupos/<int:pk>/eliminar", views.delete_group, name="delete-group"),
    path(
        "grupos/<int:pk>/detalle", views.GrupoDetailView.as_view(), name="detail-group"
    ),
    path("grupos/cargar-profesores/", views.load_professors, name="load-profesors"),
    path(
        "grupos/<int:pk>/cargar-profesores/",
        views.load_professors,
        name="load-profesors",
    ),
    path(
        "grupos/<int:pk>/cargar-horas-disponibles/",
        views.load_available_hours,
        name="load-hours",
    ),
    path("grupos/cargar-grupo/", views.load_group, name="load-group"),
]

src/django/profiles/urls.py
from django.urls import path
from . import views
from estudiantes import views as estudiantes
from profesores import views as profesores

app_name = "profiles"

urlpatterns = [
    path("", views.profile, name=""),
    path("editar", views.UpdateProfile.as_view(), name="update"),
    path(
        "estudiante/<slug>/editar",
        estudiantes.AlumnoUpdateView.as_view(),
        name="update-student",
    ),
    path(
        "profesor/<slug>/editar",
        profesores.ProfesorUpdateView.as_view(),
        name="update-professor",
    ),
    path("usuarios", views.ProfessorsAndStudents.as_view(), name="users"),
]

src/django/salones/urls.py
from django.urls import path
from .views import (
    SalonesCreateView,
    SalonesListView,
    SalonesDetailView,
    SalonesUpdateView,
    SalonesDeleteView,
)


app_name = "salones"

urlpatterns = [
    path("", SalonesListView.as_view(), name="classrooms"),
    path("nuevo", SalonesCreateView.as_view(), name="create-classroom"),
    path("<int:pk>/detalle", SalonesDetailView.as_view(), name="detail-classroom"),
    path("<int:pk>/editar", SalonesUpdateView.as_view(), name="update-classroom"),
    path("<int:pk>/eliminar", SalonesDeleteView.as_view(), name="delete-classroom"),
]

src/django/templates/base/components/bottomnav.html
<div class="lg:hidden md:hidden fixed z-50 w-full h-16 max-w-lg -translate-x-1/2 rounded-full bottom-4 left-1/2 bg-gray-900 border-gray-700 border">
    <div class="grid h-full max-w-lg grid-cols-5 mx-auto">
        <button data-tooltip-target="tooltip-home" type="button" class="inline-flex flex-col items-center justify-center px-5 rounded-s-full hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-1 text-gray-400 group-hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
            </svg>
            <span class="sr-only">Home</span>
        </button>
        <div id="tooltip-home" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
            Home
            <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
        <button data-tooltip-target="tooltip-wallet" type="button" class="inline-flex flex-col items-center justify-center px-5 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-1 text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M11.074 4 8.442.408A.95.95 0 0 0 7.014.254L2.926 4h8.148ZM9 13v-1a4 4 0 0 1 4-4h6V6a1 1 0 0 0-1-1H1a1 1 0 0 0-1 1v13a1 1 0 0 0 1 1h17a1 1 0 0 0 1-1v-2h-6a4 4 0 0 1-4-4Z"/>
                <path d="M19 10h-6a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1Zm-4.5 3.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2ZM12.62 4h2.78L12.539.41a1.086 1.086 0 1 0-1.7 1.352L12.62 4Z"/>
            </svg>
            <span class="sr-only">Wallet</span>
        </button>
        <div id="tooltip-wallet" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
            Wallet
            <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
        <div class="flex items-center justify-center">
            <button data-tooltip-target="tooltip-new" type="button" class="inline-flex items-center justify-center w-10 h-10 font-medium bg-blue-600 rounded-full hover:bg-blue-700 group focus:ring-4 focus:ring-blue-300 focus:outline-none dark:focus:ring-blue-800">
                <svg class="w-4 h-4 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
                </svg>
                <span class="sr-only">New item</span>
            </button>
        </div>
        <div id="tooltip-new" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
            Create new item
            <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
        <button data-tooltip-target="tooltip-settings" type="button" class="inline-flex flex-col items-center justify-center px-5 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-1 text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 12.25V1m0 11.25a2.25 2.25 0 0 0 0 4.5m0-4.5a2.25 2.25 0 0 1 0 4.5M4 19v-2.25m6-13.5V1m0 2.25a2.25 2.25 0 0 0 0 4.5m0-4.5a2.25 2.25 0 0 1 0 4.5M10 19V7.75m6 4.5V1m0 11.25a2.25 2.25 0 1 0 0 4.5 2.25 2.25 0 0 0 0-4.5ZM16 19v-2"/>
            </svg>
            <span class="sr-only">Settings</span>
        </button>
        <div id="tooltip-settings" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
            Settings
            <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
        <button data-tooltip-target="tooltip-profile" type="button" class="inline-flex flex-col items-center justify-center px-5 rounded-e-full hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-1 text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm0 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 13a8.949 8.949 0 0 1-4.951-1.488A3.987 3.987 0 0 1 9 13h2a3.987 3.987 0 0 1 3.951 3.512A8.949 8.949 0 0 1 10 18Z"/>
            </svg>
            <span class="sr-only">Profile</span>
        </button>
        <div id="tooltip-profile" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
            Profile
            <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
    </div>
</div>

src/django/templates/base/components/navbar.html
{% load static %}

<nav class="fixed top-0 z-50 w-full h-16 bg-black-900 dark:bg-gray-800 dark:border-gray-700">
	<div class="px-3 py-3 lg:px-5 lg:pl-3">
	  <div class="flex items-center justify-between">
		<div class="flex items-center justify-start rtl:justify-end">
		  <button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex items-center p-2 text-sm text-gray-400 rounded sm:hidden hover:bg-accent-100 hover:text-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-200">
			  <span class="sr-only">Open sidebar</span>
			  <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
				 <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
			  </svg>
		   </button>
		  <a href="{% url 'home' %}" class="flex ms-2 md:me-24">
			<img src="{% static 'assets/conservatorio-rodo-logo-beige-512px.png' %}" class="h-12 me-3" alt="Conservatorio Rodó Logo" />
		  </a>
		</div>
		<div class="flex items-center">
			<div class="flex items-center ms-3">
			  <div>
				<button type="button" class="flex text-sm bg-gray-800 rounded-full focus:ring-4 focus:ring-gray-300" aria-expanded="false" data-dropdown-toggle="dropdown-user">
				  <span class="sr-only">Open user menu</span>
				  {% include 'base/components/avatars/placeholder_initials.html' with first_name=request.user.first_name last_name=request.user.last_name %}
				</button>
			  </div>
			  <div class="z-50 hidden my-4 text-base list-none bg-gray-900 divide-y divide-gray-100 rounded shadow" id="dropdown-user">
				<div class="px-4 py-3" role="none">
				  <p class="text-sm text-gray-400 dark:text-white" role="none">
					{{request.user.username}}
				  </p>
				  <p class="text-sm font-medium text-gray-400 truncate" role="none">
					{{request.user.email}}
				  </p>
				</div>
				<ul class="py-1" role="none">
				  <li>
					<a href="{% url 'home' %}" class="block px-4 py-2 text-sm text-gray-400 hover:text-gray-900 hover:bg-accent-500" role="menuitem">Home</a>
				  </li>
				  {% if role == "staff" %}
				  <li>
					<a href="{% url 'profiles:' %}" class="block px-4 py-2 text-sm text-gray-400 hover:text-gray-900 hover:bg-accent-500" role="menuitem">Perfil</a>
				  </li>
				  
				  <li>
					<a href="{% url 'admin:index' %}" class="block px-4 py-2 text-sm text-gray-400 hover:text-gray-900 hover:bg-accent-500" role="menuitem">Admin</a>
				  </li>
				  {% endif %}
				  <li>
					<a href="{% url 'logout' %}" class="block px-4 py-2 text-sm text-gray-400 hover:text-gray-900 hover:bg-accent-500" role="menuitem">Salir</a>
				  </li>
				</ul>
			  </div>
			</div>
		  </div>
	  </div>
	</div>
  </nav>
  

src/django/templates/base/components/sidebar.html
{% load static %}

<aside
  id="default-sidebar"
  class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-black-900 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700"
  aria-label="Sidebar"
>
  <div class="flex flex-col justify-between h-full px-3 py-4 overflow-y-auto bg-black-900">
    <ul class="space-y-2 font-medium">
      <li>
        <a
          href="{% url 'home' %}"
          class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="w-6 h-6 text-gray-400 transition duration-75 dark:text-white group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              fill-rule="evenodd"
              d="M11.293 3.293a1 1 0 0 1 1.414 0l6 6 2 2a1 1 0 0 1-1.414 1.414L19 12.414V19a2 2 0 0 1-2 2h-3a1 1 0 0 1-1-1v-3h-2v3a1 1 0 0 1-1 1H7a2 2 0 0 1-2-2v-6.586l-.293.293a1 1 0 0 1-1.414-1.414l2-2 6-6Z"
              clip-rule="evenodd"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900"
            >Home</span
          >
        </a>
      </li>
      {% if role == "staff"%}
      <li>
        <a
          href="{% url 'careers' %}"
          class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="w-6 h-6 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              fill-rule="evenodd"
              d="M11 4.717c-2.286-.58-4.16-.756-7.045-.71A1.99 1.99 0 0 0 2 6v11c0 1.133.934 2.022 2.044 2.007 2.759-.038 4.5.16 6.956.791V4.717Zm2 15.081c2.456-.631 4.198-.829 6.956-.791A2.013 2.013 0 0 0 22 16.999V6a1.99 1.99 0 0 0-1.955-1.993c-2.885-.046-4.76.13-7.045.71v15.081Z"
              clip-rule="evenodd"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900"
            >Cursos y carreras</span
          >
        </a>
      </li>
      <li>
        <a
          href="{% url 'profiles:users' %}"
          class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 20 18"
          >
            <path
              d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900"
            >Usuarios</span
          >
        </a>
      </li>
      <li>
        <a
          href="{% url 'clases:list-groups' %}"
          class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="w-6 h-6 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              fill-rule="evenodd"
              d="M12 6a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm-1.5 8a4 4 0 0 0-4 4 2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-3Zm6.82-3.096a5.51 5.51 0 0 0-2.797-6.293 3.5 3.5 0 1 1 2.796 6.292ZM19.5 18h.5a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-1.1a5.503 5.503 0 0 1-.471.762A5.998 5.998 0 0 1 19.5 18ZM4 7.5a3.5 3.5 0 0 1 5.477-2.889 5.5 5.5 0 0 0-2.796 6.293A3.501 3.501 0 0 1 4 7.5ZM7.1 12H6a4 4 0 0 0-4 4 2 2 0 0 0 2 2h.5a5.998 5.998 0 0 1 3.071-5.238A5.505 5.505 0 0 1 7.1 12Z"
              clip-rule="evenodd"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900"
            >Grupos</span
          >
        </a>
      </li>
      <li>
        <a
          href="{% url 'salones:classrooms' %}"
          class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              fill-rule="evenodd"
              d="M4 4a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2v14a1 1 0 1 1 0 2H5a1 1 0 1 1 0-2V5a1 1 0 0 1-1-1Zm5 2a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1H9Zm5 0a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1h-1Zm-5 4a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1H9Zm5 0a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1h-1Zm-3 4a2 2 0 0 0-2 2v3h2v-3h2v3h2v-3a2 2 0 0 0-2-2h-2Z"
              clip-rule="evenodd"
            />
          </svg>

          <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900"
            >Salones</span
          >
        </a>
      </li>
      {% endif %}
      <li>
        <a
          href="{% url 'logout' %}"
          class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="w-6 h-6 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="none"
            viewBox="0 0 24 24"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M20 12H8m12 0-4 4m4-4-4-4M9 4H7a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h2"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900"
            >Salir</span
          >
        </a>
      </li>
    </ul>
    <div>
      <div class="flex justify-center mb-2">
        <p class="text-gray-700 text-xs">Portal 0.1.0 </p>
      </div>
      <div class="flex justify-center">
        <a href="https://www.instagram.com/conservatorio.rodo/" class="text-gray-500 hover:text-accent-500 dark:hover:text-white">
          <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path fill="currentColor" fill-rule="evenodd" d="M3 8a5 5 0 0 1 5-5h8a5 5 0 0 1 5 5v8a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5V8Zm5-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V8a3 3 0 0 0-3-3H8Zm7.597 2.214a1 1 0 0 1 1-1h.01a1 1 0 1 1 0 2h-.01a1 1 0 0 1-1-1ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm-5 3a5 5 0 1 1 10 0 5 5 0 0 1-10 0Z" clip-rule="evenodd"/>
            </svg>
            
          <span class="sr-only">Instagram</span>
      </a>
      <a href="https://www.facebook.com/conservatorio.rodo/?_rdr" class="text-gray-500 hover:text-accent-500 dark:hover:text-white ms-5">
          <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M13.135 6H15V3h-1.865a4.147 4.147 0 0 0-4.142 4.142V9H7v3h2v9.938h3V12h2.021l.592-3H12V6.591A.6.6 0 0 1 12.592 6h.543Z" clip-rule="evenodd"/>
            </svg>
            
          <span class="sr-only">Facebook</span>
      </a>
      <a href="https://www.linkedin.com/company/conservatorio-rod%C3%B3/" class="text-gray-500 hover:text-accent-500 dark:hover:text-white ms-5">
          <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M12.51 8.796v1.697a3.738 3.738 0 0 1 3.288-1.684c3.455 0 4.202 2.16 4.202 4.97V19.5h-3.2v-5.072c0-1.21-.244-2.766-2.128-2.766-1.827 0-2.139 1.317-2.139 2.676V19.5h-3.19V8.796h3.168ZM7.2 6.106a1.61 1.61 0 0 1-.988 1.483 1.595 1.595 0 0 1-1.743-.348A1.607 1.607 0 0 1 5.6 4.5a1.601 1.601 0 0 1 1.6 1.606Z" clip-rule="evenodd"/>
              <path d="M7.2 8.809H4V19.5h3.2V8.809Z"/>
            </svg>
            
          <span class="sr-only">LinkedIn</span>
      </a>
      </div>
    </div>
  </div>
</aside>