src/django/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy


from . import views

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path(
            "accounts/login/",
            auth_views.LoginView.as_view(
                redirect_authenticated_user=True, next_page="home"
            ),
            name="login",
        ),
        path(
            "accounts/logout/",
            auth_views.LogoutView.as_view(next_page="login"),
            name="logout",
        ),
        path(
            "accounts/password-reset/",
            auth_views.PasswordResetView.as_view(),
            name="password_reset",
        ),
        path(
            "accounts/password-reset/done/",
            auth_views.PasswordResetDoneView.as_view(),
            name="password_reset_done",
        ),
        path(
            "accounts/reset/<uidb64>/<token>/",
            auth_views.PasswordResetConfirmView.as_view(),
            name="password_reset_confirm",
        ),
        path(
            "accounts/reset/done/",
            auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete",
        ),
        path(
            "accounts/password-change",
            views.CustomPasswordChangeView.as_view(),
            name="password-change",
        ),
        path("", RedirectView.as_view(url=reverse_lazy("home"))),
        path(
            "app/",
            include(
                [
                    path("", views.home, name="home"),
                    path("busqueda/", views.Search.as_view(), name="search"),
                    path("administracion/", views.dashboard, name="dashboard"),
                    path("carreras/", include("carreras.urls")),
                    path("profesores/", include("profesores.urls")),
                    path("salones/", include("salones.urls")),
                    path("clases/", include("clases.urls")),
                    path("perfil/", include("profiles.urls")),
                    path("estudiantes/", include("estudiantes.urls")),
                    path("pagos/", include("pagos.urls")),
                ]
            ),
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

src/django/clases/urls.py
from django.urls import path
from . import views

app_name = "clases"

urlpatterns = [
    path(
        "bloques/crear/<int:pk>/",
        views.CreateBloqueDeClase.as_view(),
        name="create-class-block",
    ),
    path("bloques/", views.ListBloqueDeClases.as_view(), name="list-class-blocks"),
    path(
        "bloques/<int:pk>/detalle",
        views.DetailBloqueDeClase.as_view(),
        name="detail-class-block",
    ),
    path(
        "bloques/<int:pk>/editar",
        views.BloqueClaseUpdateView.as_view(),
        name="update-class-block",
    ),
    path(
        "bloques/<int:pk>/eliminar",
        views.DeleteBloqueDeClase.as_view(),
        name="delete-class-block",
    ),
    path("", views.list_groups, name="list-groups"),
    path("grupos/crear", views.CreateGrupo.as_view(), name="create-group"),
    path("grupos/<int:pk>/editar", views.UpdateGrupo.as_view(), name="update-group"),
    path("grupos/<int:pk>/eliminar", views.delete_group, name="delete-group"),
    path(
        "grupos/<int:pk>/detalle", views.GrupoDetailView.as_view(), name="detail-group"
    ),
    path("grupos/cargar-profesores/", views.load_professors, name="load-profesors"),
    path(
        "grupos/<int:pk>/cargar-profesores/",
        views.load_professors,
        name="load-profesors",
    ),
    path(
        "grupos/<int:pk>/cargar-horas-disponibles/",
        views.load_available_hours,
        name="load-hours",
    ),
    path("grupos/cargar-grupo/", views.load_group, name="load-group"),
]

src/django/clases/models.py
from django.db import models

# Create your models here.

src/django/clases/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from domain.models import BloqueDeClase, Grupo, Profesor
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import CreateGroupForm, BloqueDeClaseForm
from datetime import datetime, timedelta
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


class ListBloqueDeClases(LoginRequiredMixin, ListView):
    model = BloqueDeClase
    template_name = "clases/clases_list.html"
    context_object_name = "lista_clases"


class DetailBloqueDeClase(LoginRequiredMixin, DetailView):
    model = BloqueDeClase
    template_name = "clases/clases_list.html"


class DeleteBloqueDeClase(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = BloqueDeClase
    template_name = "clases/clases_confirm_delete.html"
    success_message = "El grupo se eliminó con éxito"

    def get_success_url(self):
        return reverse("clases:detail-group", kwargs={"pk": self.get_object().grupo.pk})

    def get_context_data(self, **kwargs):
        context = super(DeleteBloqueDeClase, self).get_context_data(**kwargs)
        bloque_de_clase = self.get_object()
        context["bloque"] = bloque_de_clase
        context["grupo_pk"] = bloque_de_clase.grupo.pk
        return context


@login_required
def delete_group(request, pk):
    grupo = get_object_or_404(Grupo, id=pk)
    if request.method == "POST":
        grupo.delete()
        return redirect(reverse_lazy("clases:list-groups"))
    return render(request, "clases/grupo_confirm_delete.html", {"grupo": grupo})


def list_groups(request):
    grupos = Grupo.objects.all()
    return render(request, "clases/grupo_list.html", {"lista_grupos": grupos})


# se agrego pk del grupo en caso que sea un update de profesor
## de grupo, para que pueda llegar aca la request y filtrar profesores
## por curso
def load_professors(request, pk=None):
    curso_id = request.GET.get("curso")
    profesores = Profesor.objects.filter(cursos__id=curso_id)
    return render(request, "clases/profesores_options.html", {"profesores": profesores})


def load_group(request):
    id_grupo = request.GET.get("grupo")
    grupo = Grupo.objects.get(pk=id_grupo)
    return render(
        request, "clases/partials/info_grupo_enrolment_modal.html", {"grupo": grupo}
    )


def load_available_hours(request, pk=None):
    selected_days = []
    selected_salon = []
    selected_hours = []
    all_time_slots = []
    bloque_id = None
    start_time = datetime.strptime("00:00", "%H:%M")  # Start at midnight (00:00)
    end_time = datetime.strptime("23:59", "%H:%M")  # End just before midnight (23:59)
    while start_time <= end_time:
        all_time_slots.append(start_time)
        start_time += timedelta(minutes=30)
    simple_time_slots = [slot.strftime("%H:%M") for slot in all_time_slots]
    horas_para_dropdown = simple_time_slots
    horas_para_dropdown = {
        hour: "bloque-available bg-gray-900" for hour in simple_time_slots
    }
    if "id" in request.GET and request.GET.get("id") != "":
        bloque_id = request.GET.get("id")
        selected_hours.append(
            BloqueDeClase.objects.get(pk=bloque_id).hora_inicio.strftime("%H:%M")
        )
        selected_hours.append(
            BloqueDeClase.objects.get(pk=bloque_id).hora_fin.strftime("%H:%M")
        )
    if "salon" in request.GET and request.GET.get("salon") != "":
        selected_salon = request.GET.getlist("salon")
        if "dia" in request.GET:
            selected_days = request.GET.getlist("dia")
        horas_no_disponibles = []
        bloques = BloqueDeClase.objects.filter(salon__id=selected_salon[0])
        selected_days = [int(day) for day in selected_days]
        q_objects = Q()
        for day_id in selected_days:
            q_objects |= Q(dia__id=day_id)
        bloques = bloques.filter(q_objects)
        if bloques:
            horas_no_disponibles.extend(
                [
                    (
                        bloque.hora_inicio.strftime("%H:%M"),
                        bloque.hora_fin.strftime("%H:%M"),
                    )
                    for bloque in bloques
                ]
            )
            all_intervals = set()
            for start, end in horas_no_disponibles:
                intervals = get_minutes_in_range(start, end)
                all_intervals.update(intervals)

            horas_no_disponibles_formateadas = []
            for minutes in sorted(all_intervals):
                hours, mins = divmod(minutes, 60)
                formatted_hour = f"{hours:02}:{mins:02}"
                horas_no_disponibles_formateadas.append(formatted_hour)

            horas_para_dropdown = {
                hour: "bloque-available bg-gray-900"
                if hour not in horas_no_disponibles_formateadas
                else "bloque-taken"
                for hour in simple_time_slots
            }
    horas_para_dropdown.update(
        {hour: "selected" for hour in horas_para_dropdown if hour in selected_hours}
    )
    return render(
        request,
        "clases/horas_options.html",
        {"horas_para_dropdown": horas_para_dropdown},
    )


def convert_to_minutes(time_str):
    hours, minutes = map(int, time_str.split(":"))
    return hours * 60 + minutes


def get_minutes_in_range(start_time, end_time):
    start_minutes = convert_to_minutes(start_time)
    end_minutes = convert_to_minutes(end_time)
    return list(range(start_minutes, end_minutes + 1, 30))


class CreateGrupo(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Grupo
    form_class = CreateGroupForm
    template_name = "clases/grupo_form.html"
    success_message = "Se agregó grupo con éxito"

    def get_success_url(self):
        return reverse_lazy("clases:detail-group", kwargs={"pk": self.object.group.pk})

    def form_valid(self, form):
        curso = form.cleaned_data["curso"]
        profesores = form.cleaned_data["profesores"]
        cupo = form.cleaned_data["cupo"]
        grupo = Grupo(curso=curso, cupo=cupo)
        grupo.save()
        grupo.profesores.set(profesores)
        return redirect("clases:detail-group", pk=grupo.pk)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {"form": form})


class UpdateGrupo(LoginRequiredMixin, UpdateView):
    model = Grupo
    form_class = CreateGroupForm
    template_name = "clases/grupo_form.html"
    success_message = "Se agregó grupo con éxito"

    def get_success_url(self):
        return reverse_lazy("clases:detail-group", kwargs={"pk": self.get_object().pk})


class GrupoDetailView(LoginRequiredMixin, DetailView):
    model = Grupo
    context_object_name = "grupo"
    template_name = "clases/grupo_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grupo = self.object
        context["bloques_de_clase"] = BloqueDeClase.objects.filter(grupo=grupo)
        return context


class CreateBloqueDeClase(LoginRequiredMixin, CreateView):
    model_name = BloqueDeClase
    template_name = "clases/partials/bloque_clase_form_partial.html"
    form_class = BloqueDeClaseForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        grupo = Grupo.objects.get(pk=kwargs["pk"])
        context = {"form": form, "grupo": grupo}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = BloqueDeClaseForm(request.POST)
        grupo = Grupo.objects.get(pk=kwargs["pk"])
        if form.is_valid():
            dias = form.cleaned_data["dia"]
            hora_inicio = form.cleaned_data["hora_inicio"]
            hora_fin = form.cleaned_data["hora_fin"]
            salon = form.cleaned_data["salon"]
            bloque = BloqueDeClase.objects.create(
                hora_inicio=hora_inicio, hora_fin=hora_fin, salon=salon, grupo=grupo
            )
            bloque.dia.set(dias)
            bloque.save()
            messages.add_message(request, messages.SUCCESS, f"Clase creada con exito.")
            return HttpResponse()
        else:
            grupo = Grupo.objects.get(pk=self.kwargs["pk"])
            response = render(
                request,
                "clases/partials/bloque_clase_form_partial.html",
                {"form": form, "grupo": grupo},
            )
            response["HX-Retarget"] = "#bloque-clase-modal"
            return response


class BloqueClaseUpdateView(LoginRequiredMixin, UpdateView):
    model = BloqueDeClase
    template_name = "clases/partials/bloque_clase_update_form_partial.html"
    form_class = BloqueDeClaseForm

    def get_context_data(self, **kwargs):
        context = super(BloqueClaseUpdateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        grupo = self.object.grupo
        dias = form.cleaned_data["dia"]
        hora_inicio = form.cleaned_data["hora_inicio"]
        hora_fin = form.cleaned_data["hora_fin"]
        salon = form.cleaned_data["salon"]

        for dia_obj in dias.all():
            try:
                bloque_ya_ocupado = BloqueDeClase.objects.get(
                    dia=dia_obj,
                    hora_inicio__lt=hora_fin,
                    hora_fin__gt=hora_inicio,
                    salon=salon,
                    grupo=grupo,
                )
                if bloque_ya_ocupado != self.object:
                    messages.add_message(
                        self.request,
                        messages.ERROR,
                        "Ya existe una clase creada para el salon y el horario seleccionado.",
                    )

src/django/clases/templates/clases/components/grupo_card_component.html
<section class='col-span-3 md:col-span-2 lg:col-span-2'>
    <div class="border border-gray-700 rounded shadow bg-gray-900 mb-4">
      <div class="flex w-full max-w-full">
        <div class="flex flex-col items-start p-4 py-8 rounded">
            <div class="relative inline-flex items-center justify-center w-12 h-12 overflow-hidden rounded bg-accent-50 mb-2">
              <span class="font-medium text-white">{{grupo.curso.nombre|make_list|first}}</span>
            </div>
            <h5 class="mb-1 text-xl font-medium text-white">{{grupo.curso.nombre}}</h5>
            <span class="text-sm text-gray-400 mb-2">{{grupo.curso.descripcion}}</span>
            <span class="text-xs font-medium me-2 p-2 rounded bg-indigo-900 text-indigo-300">Grupo</span>
        </div>
        <div class="flex flex-col items-center p-4 w-full mx-auto mb-0">
          <div class="py-2 text-sm w-full p-2">
            <div>
              <p class="mr-8 mb-2 text-gray-700">
                Identificador
              </p>
              <p class="mr-8 mb-4 text-white">
                  {{grupo.identificador}}
              </p>
            </div>
            <div>
              <p class="mr-8 mb-2 text-gray-700">
                Profesores
              </p>
              <p class="mr-8 mb-4 text-white">
                {{ grupo.profesores.all|join:"; " }}
              </p>
            </div>
            {% if role == "staff" %}
            <div>
              <p class="mr-8 mb-2 text-gray-700">
                Cupo
              </p>
              <p class="mr-8 mb-4 text-white">
                {{ grupo.cupo }}
              </p>
            </div>
            {% endif %}
            <div>
              <p class="mr-8 mb-2 text-gray-700">
                Curso
              </p>
              {% if role == "staff" %}
              <a class="mr-8 mb-6 text-white hover:text-accent-500 dark:hover:text-white" href="{{grupo.curso.get_absolute_url}}">
                {{grupo.curso.nombre}}
              </a>
              {% else %}
              <p class="mr-8 mb-4 text-white">
                {{ grupo.curso.nombre }}
              </p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  
    <div class="relative overflow-x-auto mb-4 rounded border border-gray-700">
      <table class="w-full text-sm text-left rtl:text-right text-gray-400">
          <thead class="text-xs uppercase bg-gray-900 text-gray-400">
              <tr>
                  <th scope="col" class="px-6 py-3">
                      Estudiante
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Fecha de nacimiento
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Edad
                </th>
              </tr>
          </thead>
          <tbody>
              {% for student in grupo.alumnos.all %}
                  <tr class="border-b bg-gray-900 border-gray-700">
                      <td scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
                        {% if role == "staff" %}
                          <a class="hover:text-accent-500 dark:hover:text-white" href="{{student.get_absolute_url}}">{{student.apellido}}, {{student.nombre}}</a>
                        {% else %}
                        <p>{{student.apellido}}, {{student.nombre}}</p>
                        {% endif %}
                      </td>
                      <td class="px-6 py-4">
                        {% if student.fecha_nacimiento != None %}
                          <p>{{student.fecha_nacimiento}}</p>
                        {% else %}
                          <p>N/A</p>
                        {% endif %}
                      </td>
                      <td class="px-6 py-4">
                        {% if student.age != None %}
                          <p>{{student.age}}</p>
                        {% else %}
                          <p>N/A</p>
                        {% endif %}
                      </td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
    </div>

    <div class="relative overflow-x-auto mb-4 rounded border border-gray-700">
      <table class="w-full text-sm text-left rtl:text-right text-gray-400">
          <thead class="text-xs uppercase bg-gray-900 text-gray-400">
              <tr>
                  <th scope="col" class="px-6 py-3">
                      Día
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Hora de inicio
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Hora de finalización
                </th>
                <th scope="col" class="px-6 py-3">
                  Salón
                </th>
                {% if role == "staff" %}
                <th scope="col" class="px-6 py-3">
                  Acciones
                </th>
                {% endif %}
              </tr>
          </thead>
          <tbody>
              {% for bloque in bloques_de_clase %}
                  <tr class="border-b bg-gray-900 border-gray-700">
                      <th scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
                          <p>{{ bloque.dia.all|join:", " }}</p>
                      </th>
                      <td class="px-6 py-4">
                        <p>{{bloque.hora_inicio}}</p>
                      </td>
                      <td class="px-6 py-4">
                        <p>{{bloque.hora_fin}}</p>
                      </td>
                      <td class="px-6 py-4">
                        <p>{{bloque.salon}}</p>
                      </td>
                      {% if role == "staff" %}
                      <td class="px-6 py-4">
                        <p style="text-align: center;">
                          <a style="display: inline-block" href="#" hx-get="{% url 'clases:update-class-block' bloque.pk  %}" hx-trigger="click" hx-swap="innerHTML" hx-target="#bloque-clase-modal" data-modal-target="bloque-clase-modal" data-modal-toggle="bloque-clase-modal" >
                            <svg class="w-6 h-6 text-white  hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                              <path fill-rule="evenodd" d="M11.32 6.176H5c-1.105 0-2 .949-2 2.118v10.588C3 20.052 3.895 21 5 21h11c1.105 0 2-.948 2-2.118v-7.75l-3.914 4.144A2.46 2.46 0 0 1 12.81 16l-2.681.568c-1.75.37-3.292-1.263-2.942-3.115l.536-2.839c.097-.512.335-.983.684-1.352l2.914-3.086Z" clip-rule="evenodd"/>
                              <path fill-rule="evenodd" d="M19.846 4.318a2.148 2.148 0 0 0-.437-.692 2.014 2.014 0 0 0-.654-.463 1.92 1.92 0 0 0-1.544 0 2.014 2.014 0 0 0-.654.463l-.546.578 2.852 3.02.546-.579a2.14 2.14 0 0 0 .437-.692 2.244 2.244 0 0 0 0-1.635ZM17.45 8.721 14.597 5.7 9.82 10.76a.54.54 0 0 0-.137.27l-.536 2.84c-.07.37.239.696.588.622l2.682-.567a.492.492 0 0 0 .255-.145l4.778-5.06Z" clip-rule="evenodd"/>
                            </svg>
                          </a>
                           <a  style="display: inline-block" href="#" hx-get="{% url 'clases:delete-class-block' bloque.pk  %}"  hx-trigger="click" hx-swap="innerHTML" hx-target="#confirm-form" data-modal-target="confirm-modal" data-modal-toggle="confirm-modal" ><svg class="w-6 h-6 text-white  hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                            <svg class="w-6 h-6 text-white  hover:text-accent-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                              <path fill-rule="evenodd" d="M8.586 2.586A2 2 0 0 1 10 2h4a2 2 0 0 1 2 2v2h3a1 1 0 1 1 0 2v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8a1 1 0 0 1 0-2h3V4a2 2 0 0 1 .586-1.414ZM10 6h4V4h-4v2Zm1 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Zm4 0a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Z" clip-rule="evenodd"/>
                            </svg>
                          </a>
                        </p>
                      </td>
                      {% endif %}
                  </tr>
              {% endfor %}
          </tbody>
      </table>
    </div>
    {% if role == "staff" %}
    <div class="flex flex-col items-center p-4 w-full mx-auto mb-0  border border-gray-700 rounded shadow bg-gray-900">
      <ul class="py-2 text-sm text-gray-700 dark:text-gray-200 w-full" aria-labelledby="dropdownHoverButton">
        <li>
            <a href="{% url 'clases:update-group' grupo.pk %}" class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group border border-gray-700 mb-1">
            <svg class="w-6 h-6 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd" d="M11.32 6.176H5c-1.105 0-2 .949-2 2.118v10.588C3 20.052 3.895 21 5 21h11c1.105 0 2-.948 2-2.118v-7.75l-3.914 4.144A2.46 2.46 0 0 1 12.81 16l-2.681.568c-1.75.37-3.292-1.263-2.942-3.115l.536-2.839c.097-.512.335-.983.684-1.352l2.914-3.086Z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M19.846 4.318a2.148 2.148 0 0 0-.437-.692 2.014 2.014 0 0 0-.654-.463 1.92 1.92 0 0 0-1.544 0 2.014 2.014 0 0 0-.654.463l-.546.578 2.852 3.02.546-.579a2.14 2.14 0 0 0 .437-.692 2.244 2.244 0 0 0 0-1.635ZM17.45 8.721 14.597 5.7 9.82 10.76a.54.54 0 0 0-.137.27l-.536 2.84c-.07.37.239.696.588.622l2.682-.567a.492.492 0 0 0 .255-.145l4.778-5.06Z" clip-rule="evenodd"/>
            </svg>
            <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900">Editar grupo</span>
            <svg class="inline-flex items-center justify-center px-2 ms-3 text-sm font-medium text-gray-400 dark:bg-gray-700 dark:text-gray-300 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 5 7 7-7 7"/>
            </svg>
        </a>
        </li>
        <li>
            <a href="#" hx-get="{% url 'clases:create-class-block' grupo.pk  %}" hx-trigger="click" hx-swap="innerHTML" hx-target="#bloque-clase-modal" data-modal-target="bloque-clase-modal" data-modal-toggle="bloque-clase-modal"  class="flex items-center p-2 text-gray-400 rounded dark:text-white hover:bg-accent-100 dark:hover:bg-gray-700 group border border-gray-700 mb-1">
            <svg class="w-6 h-6 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd" d="M11.32 6.176H5c-1.105 0-2 .949-2 2.118v10.588C3 20.052 3.895 21 5 21h11c1.105 0 2-.948 2-2.118v-7.75l-3.914 4.144A2.46 2.46 0 0 1 12.81 16l-2.681.568c-1.75.37-3.292-1.263-2.942-3.115l.536-2.839c.097-.512.335-.983.684-1.352l2.914-3.086Z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M19.846 4.318a2.148 2.148 0 0 0-.437-.692 2.014 2.014 0 0 0-.654-.463 1.92 1.92 0 0 0-1.544 0 2.014 2.014 0 0 0-.654.463l-.546.578 2.852 3.02.546-.579a2.14 2.14 0 0 0 .437-.692 2.244 2.244 0 0 0 0-1.635ZM17.45 8.721 14.597 5.7 9.82 10.76a.54.54 0 0 0-.137.27l-.536 2.84c-.07.37.239.696.588.622l2.682-.567a.492.492 0 0 0 .255-.145l4.778-5.06Z" clip-rule="evenodd"/>
            </svg>
            <span class="flex-1 ms-3 whitespace-nowrap group-hover:text-gray-900">Agregar clases</span>
            <svg class="inline-flex items-center justify-center px-2 ms-3 text-sm font-medium text-gray-400 dark:bg-gray-700 dark:text-gray-300 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 5 7 7-7 7"/>
            </svg>
        </a>
        </li>
      </ul>
    </div>
    {% endif %}
  </section>